'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewEditInstallation
    
    '''<summary>
    '''hidden_installationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidden_installationID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbl_topCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_topCreatedBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbl_topEditedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_topEditedBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btn_saveChanges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_saveChanges As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''combo_ZNSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_ZNSalesPerson As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ds_forumSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_forumSalesPerson As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''combo_ZNEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_ZNEngineer As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ds_forumEngineer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_forumEngineer As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tb_vendorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_vendorAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorAddress As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_vendorAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorAddress2 As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_vendorPostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorPostCode As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''combo_vendorState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_vendorState As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''combo_vendorCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_vendorCountry As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''tb_vendorContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorContactName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_vendorContactNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorContactNumber As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_vendorContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_vendorContactEmail As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cb_archiveAndViewer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_archiveAndViewer As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''cb_glaucomaWorkplaceMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_glaucomaWorkplaceMain As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''cb_retinaWorkplaceMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_retinaWorkplaceMain As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''spin_forumViewers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spin_forumViewers As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''spin_glaucomaWorkplaceUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spin_glaucomaWorkplaceUsers As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''spin_retinaWorkplaceUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spin_retinaWorkplaceUsers As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''spin_zeissDeviceConnections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spin_zeissDeviceConnections As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''spin_thirdPartyDeviceConnections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spin_thirdPartyDeviceConnections As Global.DevExpress.Web.ASPxSpinEdit
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cb_emrRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_emrRequired As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''combo_EMRVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_EMRVendors As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ds_emrVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_emrVendors As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''cb_dataCleanseRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_dataCleanseRequired As Global.DevExpress.Web.ASPxCheckBox
    
    '''<summary>
    '''tb_notesandRequests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_notesandRequests As Global.DevExpress.Web.ASPxMemo
End Class
