'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateEditUserAccounts
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tb_newFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_newFirstName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_newLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_newLastName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_newEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_newEmail As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_newNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_newNumber As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''combo_newReportingDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_newReportingDivision As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ds_reportingDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_reportingDivision As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dl_newUserRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dl_newUserRoles As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''btn_newSaveUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_newSaveUser As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''combo_editUserSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_editUserSelect As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''ds_userAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_userAccounts As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''tb_editFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_editFirstName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_editLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_editLastName As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_editEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_editEmailAddress As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''tb_editContactNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_editContactNumber As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''combo_editReportDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combo_editReportDivision As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''dl_editUserRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dl_editUserRoles As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''btn_editUserSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_editUserSave As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btn_editSetUserInactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_editSetUserInactive As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btn_editDeleteUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_editDeleteUser As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btn_confirmUserDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_confirmUserDelete As Global.DevExpress.Web.ASPxButton
End Class
